services:
  pgadmin:
    image: dpage/pgadmin4
    container_name: brasileirao_pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@brasileirao.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - brasileirao_network

networks:
  brasileirao_network:
    external: true
